import { Injectable } from '@angular/core';

export interface Concelho {
  nome: string;
  distrito: string;
}

@Injectable({
  providedIn: 'root'
})
export class DistrictConselhoService {
  private concelhos: Concelho[] = [
    { nome: "Abrantes", distrito: "Santarém" },
    { nome: "Águeda", distrito: "Aveiro" },
    { nome: "Aguiar da Beira", distrito: "Guarda" },
    { nome: "Alandroal", distrito: "Évora" },
    { nome: "Albergaria-a-Velha", distrito: "Aveiro" },
    { nome: "Albufeira", distrito: "Faro" },
    { nome: "Alcácer do Sal", distrito: "Setúbal" },
    { nome: "Alcanena", distrito: "Santarém" },
    { nome: "Alcobaça", distrito: "Leiria" },
    { nome: "Alcochete", distrito: "Setúbal" },
    { nome: "Alcoutim", distrito: "Faro" },
    { nome: "Alenquer", distrito: "Lisboa" },
    { nome: "Alfândega da Fé", distrito: "Bragança" },
    { nome: "Alijó", distrito: "Vila Real" },
    { nome: "Aljezur", distrito: "Faro" },
    { nome: "Aljustrel", distrito: "Beja" },
    { nome: "Almada", distrito: "Setúbal" },
    { nome: "Almeida", distrito: "Guarda" },
    { nome: "Almeirim", distrito: "Santarém" },
    { nome: "Almodôvar", distrito: "Beja" },
    { nome: "Alpiarça", distrito: "Santarém" },
    { nome: "Alter do Chão", distrito: "Portalegre" },
    { nome: "Alvaiázere", distrito: "Leiria" },
    { nome: "Alvito", distrito: "Beja" },
    { nome: "Amadora", distrito: "Lisboa" },
    { nome: "Amarante", distrito: "Porto" },
    { nome: "Amares", distrito: "Braga" },
    { nome: "Anadia", distrito: "Aveiro" },
    { nome: "Angra do Heroísmo", distrito: "Açores" },
    { nome: "Ansião", distrito: "Leiria" },
    { nome: "Arcos de Valdevez", distrito: "Viana do Castelo" },
    { nome: "Arganil", distrito: "Coimbra" },
    { nome: "Armamar", distrito: "Viseu" },
    { nome: "Arouca", distrito: "Aveiro" },
    { nome: "Arraiolos", distrito: "Évora" },
    { nome: "Arronches", distrito: "Portalegre" },
    { nome: "Arruda dos Vinhos", distrito: "Lisboa" },
    { nome: "Aveiro", distrito: "Aveiro" },
    { nome: "Avis", distrito: "Portalegre" },
    { nome: "Azambuja", distrito: "Lisboa" },
    { nome: "Baião", distrito: "Porto" },
    { nome: "Barcelos", distrito: "Braga" },
    { nome: "Barrancos", distrito: "Beja" },
    { nome: "Barreiro", distrito: "Setúbal" },
    { nome: "Batalha", distrito: "Leiria" },
    { nome: "Beja", distrito: "Beja" },
    { nome: "Belmonte", distrito: "Castelo Branco" },
    { nome: "Benavente", distrito: "Santarém" },
    { nome: "Bombarral", distrito: "Leiria" },
    { nome: "Borba", distrito: "Évora" },
    { nome: "Boticas", distrito: "Vila Real" },
    { nome: "Braga", distrito: "Braga" },
    { nome: "Bragança", distrito: "Bragança" },
    { nome: "Cabeceiras de Basto", distrito: "Braga" },
    { nome: "Cadaval", distrito: "Lisboa" },
    { nome: "Caldas da Rainha", distrito: "Leiria" },
    { nome: "Câmara de Lobos", distrito: "Madeira" },
    { nome: "Caminha", distrito: "Viana do Castelo" },
    { nome: "Campo Maior", distrito: "Portalegre" },
    { nome: "Cantanhede", distrito: "Coimbra" },
    { nome: "Carrazeda de Ansiães", distrito: "Bragança" },
    { nome: "Carregal do Sal", distrito: "Viseu" },
    { nome: "Cartaxo", distrito: "Santarém" },
    { nome: "Cascais", distrito: "Lisboa" },
    { nome: "Castanheira de Pera", distrito: "Leiria" },
    { nome: "Castelo Branco", distrito: "Castelo Branco" },
    { nome: "Castelo de Paiva", distrito: "Aveiro" },
    { nome: "Castelo de Vide", distrito: "Portalegre" },
    { nome: "Castro Daire", distrito: "Viseu" },
    { nome: "Castro Marim", distrito: "Faro" },
    { nome: "Castro Verde", distrito: "Beja" },
    { nome: "Celorico da Beira", distrito: "Guarda" },
    { nome: "Celorico de Basto", distrito: "Braga" },
    { nome: "Chamusca", distrito: "Santarém" },
    { nome: "Chaves", distrito: "Vila Real" },
    { nome: "Cinfães", distrito: "Viseu" },
    { nome: "Coimbra", distrito: "Coimbra" },
    { nome: "Condeixa-a-Nova", distrito: "Coimbra" },
    { nome: "Constância", distrito: "Santarém" },
    { nome: "Coruche", distrito: "Santarém" },
    { nome: "Corvo", distrito: "Açores" },
    { nome: "Covilhã", distrito: "Castelo Branco" },
    { nome: "Crato", distrito: "Portalegre" },
    { nome: "Cuba", distrito: "Beja" },
    { nome: "Elvas", distrito: "Portalegre" },
    { nome: "Entroncamento", distrito: "Santarém" },
    { nome: "Espinho", distrito: "Aveiro" },
    { nome: "Esposende", distrito: "Braga" },
    { nome: "Estarreja", distrito: "Aveiro" },
    { nome: "Estremoz", distrito: "Évora" },
    { nome: "Évora", distrito: "Évora" },
    { nome: "Fafe", distrito: "Braga" },
    { nome: "Faro", distrito: "Faro" },
    { nome: "Felgueiras", distrito: "Porto" },
    { nome: "Ferreira do Alentejo", distrito: "Beja" },
    { nome: "Ferreira do Zêzere", distrito: "Santarém" },
    { nome: "Figueira da Foz", distrito: "Coimbra" },
    { nome: "Figueira de Castelo Rodrigo", distrito: "Guarda" },
    { nome: "Figueiró dos Vinhos", distrito: "Leiria" },
    { nome: "Fornos de Algodres", distrito: "Guarda" },
    { nome: "Freixo de Espada à Cinta", distrito: "Bragança" },
    { nome: "Fronteira", distrito: "Portalegre" },
    { nome: "Funchal", distrito: "Madeira" },
    { nome: "Fundão", distrito: "Castelo Branco" },
    { nome: "Gavião", distrito: "Portalegre" },
    { nome: "Góis", distrito: "Coimbra" },
    { nome: "Golegã", distrito: "Santarém" },
    { nome: "Gondomar", distrito: "Porto" },
    { nome: "Gouveia", distrito: "Guarda" },
    { nome: "Grândola", distrito: "Setúbal" },
    { nome: "Guarda", distrito: "Guarda" },
    { nome: "Guimarães", distrito: "Braga" },
    { nome: "Horta", distrito: "Açores" },
    { nome: "Idanha-a-Nova", distrito: "Castelo Branco" },
    { nome: "Ílhavo", distrito: "Aveiro" },
    { nome: "Lagoa (Algarve)", distrito: "Faro" },
    { nome: "Lagoa (Açores)", distrito: "Açores" },
    { nome: "Lagos", distrito: "Faro" },
    { nome: "Lajes das Flores", distrito: "Açores" },
    { nome: "Lajes do Pico", distrito: "Açores" },
    { nome: "Lamego", distrito: "Viseu" },
    { nome: "Leiria", distrito: "Leiria" },
    { nome: "Lisboa", distrito: "Lisboa" },
    { nome: "Loulé", distrito: "Faro" },
    { nome: "Loures", distrito: "Lisboa" },
    { nome: "Lourinhã", distrito: "Lisboa" },
    { nome: "Lousã", distrito: "Coimbra" },
    { nome: "Lousada", distrito: "Porto" },
    { nome: "Mação", distrito: "Santarém" },
    { nome: "Macedo de Cavaleiros", distrito: "Bragança" },
    { nome: "Machico", distrito: "Madeira" },
    { nome: "Madalena", distrito: "Açores" },
    { nome: "Mafra", distrito: "Lisboa" },
    { nome: "Maia", distrito: "Porto" },
    { nome: "Mangualde", distrito: "Viseu" },
    { nome: "Manteigas", distrito: "Guarda" },
    { nome: "Marco de Canaveses", distrito: "Porto" },
    { nome: "Marinha Grande", distrito: "Leiria" },
    { nome: "Marvão", distrito: "Portalegre" },
    { nome: "Matosinhos", distrito: "Porto" },
    { nome: "Mealhada", distrito: "Aveiro" },
    { nome: "Mêda", distrito: "Guarda" },
    { nome: "Melgaço", distrito: "Viana do Castelo" },
    { nome: "Mértola", distrito: "Beja" },
    { nome: "Mesão Frio", distrito: "Vila Real" },
    { nome: "Mira", distrito: "Coimbra" },
    { nome: "Miranda do Corvo", distrito: "Coimbra" },
    { nome: "Miranda do Douro", distrito: "Bragança" },
    { nome: "Mirandela", distrito: "Bragança" },
    { nome: "Mogadouro", distrito: "Bragança" },
    { nome: "Moimenta da Beira", distrito: "Viseu" },
    { nome: "Moita", distrito: "Setúbal" },
    { nome: "Monção", distrito: "Viana do Castelo" },
    { nome: "Monchique", distrito: "Faro" },
    { nome: "Mondim de Basto", distrito: "Vila Real" },
    { nome: "Montalegre", distrito: "Vila Real" },
    { nome: "Montemor-o-Novo", distrito: "Évora" },
    { nome: "Montemor-o-Velho", distrito: "Coimbra" },
    { nome: "Montijo", distrito: "Setúbal" },
    { nome: "Mora", distrito: "Évora" },
    { nome: "Mortágua", distrito: "Viseu" },
    { nome: "Moura", distrito: "Beja" },
    { nome: "Mourão", distrito: "Évora" },
    { nome: "Murça", distrito: "Vila Real" },
    { nome: "Murtosa", distrito: "Aveiro" },
    { nome: "Nazaré", distrito: "Leiria" },
    { nome: "Nelas", distrito: "Viseu" },
    { nome: "Nisa", distrito: "Portalegre" },
    { nome: "Nordeste", distrito: "Açores" },
    { nome: "Óbidos", distrito: "Leiria" },
    { nome: "Odemira", distrito: "Beja" },
    { nome: "Odivelas", distrito: "Lisboa" },
    { nome: "Oeiras", distrito: "Lisboa" },
    { nome: "Oleiros", distrito: "Castelo Branco" },
    { nome: "Olhão", distrito: "Faro" },
    { nome: "Oliveira de Azeméis", distrito: "Aveiro" },
    { nome: "Oliveira de Frades", distrito: "Viseu" },
    { nome: "Oliveira do Bairro", distrito: "Aveiro" },
    { nome: "Oliveira do Hospital", distrito: "Coimbra" },
    { nome: "Ourém", distrito: "Santarém" },
    { nome: "Ourique", distrito: "Beja" },
    { nome: "Ovar", distrito: "Aveiro" },
    { nome: "Paços de Ferreira", distrito: "Porto" },
    { nome: "Palmela", distrito: "Setúbal" },
    { nome: "Pampilhosa da Serra", distrito: "Coimbra" },
    { nome: "Paredes", distrito: "Porto" },
    { nome: "Paredes de Coura", distrito: "Viana do Castelo" },
    { nome: "Pedrógão Grande", distrito: "Leiria" },
    { nome: "Penacova", distrito: "Coimbra" },
    { nome: "Penafiel", distrito: "Porto" },
    { nome: "Penalva do Castelo", distrito: "Viseu" },
    { nome: "Penamacor", distrito: "Castelo Branco" },
    { nome: "Penedono", distrito: "Viseu" },
    { nome: "Penela", distrito: "Coimbra" },
    { nome: "Peniche", distrito: "Leiria" },
    { nome: "Peso da Régua", distrito: "Vila Real" },
    { nome: "Pinhel", distrito: "Guarda" },
    { nome: "Pombal", distrito: "Leiria" },
    { nome: "Ponta Delgada", distrito: "Açores" },
    { nome: "Ponta do Sol", distrito: "Madeira" },
    { nome: "Ponte da Barca", distrito: "Viana do Castelo" },
    { nome: "Ponte de Lima", distrito: "Viana do Castelo" },
    { nome: "Ponte de Sor", distrito: "Portalegre" },
    { nome: "Portalegre", distrito: "Portalegre" },
    { nome: "Portel", distrito: "Évora" },
    { nome: "Portimão", distrito: "Faro" },
    { nome: "Porto", distrito: "Porto" },
    { nome: "Porto de Mós", distrito: "Leiria" },
    { nome: "Porto Moniz", distrito: "Madeira" },
    { nome: "Porto Santo", distrito: "Madeira" },
    { nome: "Póvoa de Lanhoso", distrito: "Braga" },
    { nome: "Póvoa de Varzim", distrito: "Porto" },
    { nome: "Povoação", distrito: "Açores" },
    { nome: "Praia da Vitória", distrito: "Açores" },
    { nome: "Proença-a-Nova", distrito: "Castelo Branco" },
    { nome: "Redondo", distrito: "Évora" },
    { nome: "Reguengos de Monsaraz", distrito: "Évora" },
    { nome: "Resende", distrito: "Viseu" },
    { nome: "Ribeira Brava", distrito: "Madeira" },
    { nome: "Ribeira de Pena", distrito: "Vila Real" },
    { nome: "Ribeira Grande", distrito: "Açores" },
    { nome: "Rio Maior", distrito: "Santarém" },
    { nome: "Sabrosa", distrito: "Vila Real" },
    { nome: "Sabugal", distrito: "Guarda" },
    { nome: "Salvaterra de Magos", distrito: "Santarém" },
    { nome: "Santa Comba Dão", distrito: "Viseu" },
    { nome: "Santa Cruz", distrito: "Madeira" },
    { nome: "Santa Cruz das Flores", distrito: "Açores" },
    { nome: "Santa Cruz da Graciosa", distrito: "Açores" },
    { nome: "Santa Maria da Feira", distrito: "Aveiro" },
    { nome: "Santa Marta de Penaguião", distrito: "Vila Real" },
    { nome: "Santana", distrito: "Madeira" },
    { nome: "Santarém", distrito: "Santarém" },
    { nome: "Santiago do Cacém", distrito: "Setúbal" },
    { nome: "Santo Tirso", distrito: "Porto" },
    { nome: "São Brás de Alportel", distrito: "Faro" },
    { nome: "São João da Madeira", distrito: "Aveiro" },
    { nome: "São João da Pesqueira", distrito: "Viseu" },
    { nome: "São Pedro do Sul", distrito: "Viseu" },
    { nome: "São Roque do Pico", distrito: "Açores" },
    { nome: "São Vicente", distrito: "Madeira" },
    { nome: "Sardoal", distrito: "Santarém" },
    { nome: "Sátão", distrito: "Viseu" },
    { nome: "Seia", distrito: "Guarda" },
    { nome: "Seixal", distrito: "Setúbal" },
    { nome: "Sernancelhe", distrito: "Viseu" },
    { nome: "Serpa", distrito: "Beja" },
    { nome: "Sertã", distrito: "Castelo Branco" },
    { nome: "Sesimbra", distrito: "Setúbal" },
    { nome: "Setúbal", distrito: "Setúbal" },
    { nome: "Sever do Vouga", distrito: "Aveiro" },
    { nome: "Silves", distrito: "Faro" },
    { nome: "Sines", distrito: "Setúbal" },
    { nome: "Sintra", distrito: "Lisboa" },
    { nome: "Sobral de Monte Agraço", distrito: "Lisboa" },
    { nome: "Soure", distrito: "Coimbra" },
    { nome: "Sousel", distrito: "Portalegre" },
    { nome: "Tábua", distrito: "Coimbra" },
    { nome: "Tabuaço", distrito: "Viseu" },
    { nome: "Tarouca", distrito: "Viseu" },
    { nome: "Tavira", distrito: "Faro" },
    { nome: "Terras de Bouro", distrito: "Braga" },
    { nome: "Tomar", distrito: "Santarém" },
    { nome: "Tondela", distrito: "Viseu" },
    { nome: "Torre de Moncorvo", distrito: "Bragança" },
    { nome: "Torres Novas", distrito: "Santarém" },
    { nome: "Torres Vedras", distrito: "Lisboa" },
    { nome: "Trancoso", distrito: "Guarda" },
    { nome: "Trofa", distrito: "Porto" },
    { nome: "Vagos", distrito: "Aveiro" },
    { nome: "Vale de Cambra", distrito: "Aveiro" },
    { nome: "Valença", distrito: "Viana do Castelo" },
    { nome: "Valongo", distrito: "Porto" },
    { nome: "Valpaços", distrito: "Vila Real" },
    { nome: "Velas", distrito: "Açores" },
    { nome: "Vendas Novas", distrito: "Évora" },
    { nome: "Viana do Alentejo", distrito: "Évora" },
    { nome: "Viana do Castelo", distrito: "Viana do Castelo" },
    { nome: "Vidigueira", distrito: "Beja" },
    { nome: "Vieira do Minho", distrito: "Braga" },
    { nome: "Vila de Rei", distrito: "Castelo Branco" },
    { nome: "Vila do Bispo", distrito: "Faro" },
    { nome: "Vila do Conde", distrito: "Porto" },
    { nome: "Vila do Porto", distrito: "Açores" },
    { nome: "Vila Flor", distrito: "Bragança" },
    { nome: "Vila Franca de Xira", distrito: "Lisboa" },
    { nome: "Vila Franca do Campo", distrito: "Açores" },
    { nome: "Vila Nova da Barquinha", distrito: "Santarém" },
    { nome: "Vila Nova de Cerveira", distrito: "Viana do Castelo" },
    { nome: "Vila Nova de Famalicão", distrito: "Braga" },
    { nome: "Vila Nova de Foz Côa", distrito: "Guarda" },
    { nome: "Vila Nova de Gaia", distrito: "Porto" },
    { nome: "Vila Nova de Paiva", distrito: "Viseu" },
    { nome: "Vila Nova de Poiares", distrito: "Coimbra" },
    { nome: "Vila Pouca de Aguiar", distrito: "Vila Real" },
    { nome: "Vila Real", distrito: "Vila Real" },
    { nome: "Vila Real de Santo António", distrito: "Faro" },
    { nome: "Vila Velha de Ródão", distrito: "Castelo Branco" },
    { nome: "Vila Verde", distrito: "Braga" },
    { nome: "Vila Viçosa", distrito: "Évora" },
    { nome: "Vimioso", distrito: "Bragança" },
    { nome: "Vinhais", distrito: "Bragança" },
    { nome: "Viseu", distrito: "Viseu" },
    { nome: "Vizela", distrito: "Braga" },
    { nome: "Vouzela", distrito: "Viseu" }
  ];

  constructor() { }

  getConcelhos(): Concelho[] {
    return this.concelhos;
  }

  getConcelhosByDistrito(distrito: string): Concelho[] {
    return this.concelhos.filter(concelho => concelho.distrito === distrito);
  }

  getDistritos(): string[] {
    return [...new Set(this.concelhos.map(concelho => concelho.distrito))].sort();
  }
}
